version: 2.1

orbs:
  win: circleci/windows@2.4.1
  aws-cli: circleci/aws-cli@2.0.3
  gh: circleci/github-cli@1.0.4

defaults: &defaults
  parameters:
    node_version:
      type: string
      default: '14.17.5'
    root_tap_tests:
      type: boolean
      default: false
    jest_tests:
      type: boolean
      default: false
    acceptance_tests:
      type: boolean
      default: false
    system_tests:
      type: boolean
      default: false
    package_tests:
      type: boolean
      default: false
  working_directory: /mnt/ramdisk/snyk

commands:
  install_project_dependencies:
    parameters:
      node_version:
        type: string
      npm_version:
        type: string
        default: '7.21.1'
      npm_cache_directory:
        type: string
        default: /mnt/ramdisk/.npm
      npm_global_sudo:
        type: boolean
        default: true
    steps:
      - restore_cache:
          name: Restoring npm cache
          keys:
            - npm-cache-v2-{{ arch }}-node<< parameters.node_version >>-npm<< parameters.npm_version >>-{{ checksum "package-lock.json" }}
      - when:
          condition:
            not: << parameters.npm_global_sudo >>
          steps:
            run:
              name: Installing npm
              command: npm install -g npm@<< parameters.npm_version >>
      - when:
          condition: << parameters.npm_global_sudo >>
          steps:
            run:
              name: Installing npm
              command: sudo npm install -g npm@<< parameters.npm_version >>
      - run:
          name: Configuring npm
          command: |
            npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
            npm config set cache << parameters.npm_cache_directory >>
            npm config set prefer-offline true
      - run:
          name: Installing project dependencies
          command: npm ci
      - save_cache:
          name: Saving npm cache
          key: npm-cache-v2-{{ arch }}-node<< parameters.node_version >>-npm<< parameters.npm_version >>-{{ checksum "package-lock.json" }}
          paths:
            - << parameters.npm_cache_directory >>
  install_sdks_windows:
    steps:
      - restore_cache:
          name: Restoring Chocolatey cache
          keys:
            - chocolatey-cache-v2-{{ arch }}-{{ checksum ".circleci/chocolatey.config" }}
      - run:
          name: Installing SDKs
          command: choco install .circleci/chocolatey.config --no-progress
      - save_cache:
          name: Saving Chocolatey cache
          key: chocolatey-cache-v2-{{ arch }}-{{ checksum ".circleci/chocolatey.config" }}
          paths:
            - ~\AppData\Local\Temp\chocolatey
  install_sdks_linux:
    steps:
      - restore_cache:
          name: Restoring SDKMAN install cache
          keys:
            - sdkman-install-cache-v3-{{ arch }}-{{ checksum ".circleci/vendor/sdkman-install.sh" }}
      - run:
          name: Installing Python
          command: |
            sudo apt update
            sudo apt install python3 python3-pip python-is-python3
      - run:
          name: Installing SDKMAN
          # The install script comes from https://get.sdkman.io/?rcupdate=false
          # We need to disable rcupdate as CircleCI uses a different setup.
          command: |
            ./.circleci/vendor/sdkman-install.sh
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
      - save_cache:
          name: Saving SDKMAN install cache
          key: sdkman-install-cache-v3-{{ arch }}-{{ checksum ".circleci/vendor/sdkman-install.sh" }}
          paths:
            - ~/.sdkman
      - restore_cache:
          name: Restoring SDKMAN archive cache
          keys:
            - sdkman-archive-cache-v3-{{ arch }}-{{ checksum ".circleci/install-sdks-linux.sh" }}
      - run:
          name: Installing SDKs
          command: ./.circleci/install-sdks-linux.sh
      - save_cache:
          name: Saving SDKMAN archive cache
          key: sdkman-archive-cache-v3-{{ arch }}-{{ checksum ".circleci/install-sdks-linux.sh" }}
          paths:
            - ~/.sdkman/archives
  install_node_windows:
    parameters:
      node_version:
        type: string
    steps:
      - run:
          name: Removing pre-installed NodeJS
          command: |
            $current_node_version = node --version
            nvm uninstall $current_node_version
      - run:
          name: Installing NodeJS
          command: choco install nodejs --version=<< parameters.node_version >> --no-progress
  install_shellspec_dependencies:
    steps:
      - run:
          name: Installing ShellSpec
          command: |
            curl -fsSL https://git.io/shellspec | sh -s -- -y
            sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
  pack_snyk_cli:
    steps:
      - run:
          name: Packing Snyk CLI
          command: |
            mkdir ./dist-pack
            cd ./dist-pack
            npm pack ..
  install_release_dependencies:
    steps:
      - run:
          name: Installing release dependencies
          command: |
            sudo apt update
            sudo apt install osslsigncode
jobs:
  lint:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - run:
          name: Linting project
          command: npm run lint
  build:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - run:
          name: Building project
          command: npm run build:prod
      - persist_to_workspace:
          root: .
          paths:
            - dist/
            - packages/*/dist
            - pysrc
  regression-test:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_sdks_linux
      - install_shellspec_dependencies
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: .
      - run:
          name: Installing test fixture dependencies
          working_directory: ./test/fixtures/basic-npm
          command: npm install
      - run:
          name: Pruning dependencies
          command: npx ts-node ./release-scripts/prune-dependencies-in-packagejson.ts
      - pack_snyk_cli
      - run:
          name: Installing packed Snyk CLI
          command: sudo npm install -g snyk-*.tgz
          path: ./dist-pack
      - run:
          name: Running ShellSpec tests
          working_directory: ./test/smoke
          command: |
            echo "Checkout the README in test/smoke folder for more details about this step"
            unset SNYK_API
            unset SNYK_API_KEY
            shellspec -f d -e REGRESSION_TEST=1
  unit-test:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    environment:
      TEMP: /mnt/ramdisk/tmp
    steps:
      - run:
          name: Creating temporary directory
          command: mkdir /mnt/ramdisk/tmp
      - checkout
      - install_sdks_linux
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: .
      - run:
          name: Configuring Snyk CLI
          command: node ./bin/snyk config set "api=${SNYK_API_KEY}"
      - run:
          name: Running unit tests (Packages)
          command: npm run test:packages-unit -- --ci
      - run:
          name: Running unit tests (Jest)
          command: npm run test:jest-unit -- --ci
      - run:
          name: Running system tests (Jest)
          command: npm run test:jest-system -- --ci
      - run:
          name: Running root tests (Jest)
          command: npm run test:jest -- --ci
  acceptance-test:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    environment:
      TEMP: /mnt/ramdisk/tmp
    steps:
      - run:
          name: Creating temporary directory
          command: mkdir /mnt/ramdisk/tmp
      - checkout
      - install_sdks_linux
      - aws-cli/install:
          version: 2.2.32
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: .
      - run:
          name: Configuring Snyk CLI
          command: node ./bin/snyk config set "api=${SNYK_API_KEY}"
      - run:
          name: Running acceptance tests (Packages)
          command: npm run test:packages-acceptance -- --ci
      - run:
          name: Running acceptance tests (Jest)
          command: npm run test:jest-acceptance -- --ci
  tap-test:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    environment:
      TEMP: /mnt/ramdisk/tmp
    steps:
      - run:
          name: Creating temporary directory
          command: mkdir /mnt/ramdisk/tmp
      - checkout
      - install_sdks_linux
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: .
      - run:
          name: Configuring Snyk CLI
          command: node ./bin/snyk config set "api=${SNYK_API_KEY}"
      - run:
          name: Running root tests (Tap)
          command: npm run test:test
      - run:
          name: Running system tests (Tap)
          command: npm run test:system
      - run:
          name: Running acceptance tests (Tap)
          command: npm run test:acceptance
  test-windows:
    <<: *defaults
    executor: win/default
    working_directory: ~\snyk
    steps:
      - run:
          name: Configuring Git
          command: git config --global core.autocrlf false
      - checkout
      - install_node_windows:
          node_version: << parameters.node_version >>
      - install_sdks_windows
      - install_project_dependencies:
          npm_cache_directory: ~\AppData\Local\npm-cache
          node_version: << parameters.node_version >>
          npm_global_sudo: false
      - attach_workspace:
          at: .
      - run:
          name: Configuring Snyk CLI
          command: node ./bin/snyk config set "api=$env:SNYK_API_KEY"
      - when:
          condition: << parameters.package_tests >>
          steps:
            - run:
                name: Running unit tests (Packages)
                command: npm run test:packages-unit -- --ci
      - when:
          condition: << parameters.package_tests >>
          steps:
            - run:
                name: Running acceptance tests (Packages)
                command: npm run test:packages-acceptance -- --ci
      - when:
          condition: << parameters.root_tap_tests >>
          steps:
            - run:
                name: Running root tests (Tap)
                command: npm run test:test
      - when:
          condition: << parameters.jest_tests >>
          steps:
            - run:
                name: Running root tests (Jest)
                command: npm run test:jest -- --ci
            - run:
                name: Running unit tests (Jest)
                command: npm run test:jest-unit -- --ci
            - run:
                name: Running system tests (Jest)
                command: npm run test:jest-system -- --ci
            - run:
                name: Download AWS CLI
                command: |
                  msiexec.exe /i AWSCLIV2.msi /quiet
                  [Environment]::SetEnvironmentVariable("Path", $env:PATH + `
                  ";c:\Program Files\Amazon\AWSCLIV2", "Machine")
                shell: powershell.exe
            - run:
                name: Running acceptance tests (Jest)
                command: npm run test:jest-acceptance -- --ci
      - when:
          condition: << parameters.acceptance_tests >>
          steps:
            - run:
                name: Running acceptance tests (Tap)
                command: npm run test:acceptance
      - when:
          condition: << parameters.system_tests >>
          steps:
            - run:
                name: Running system tests (Tap)
                command: npm run test:system
  dev-release:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_release_dependencies
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: .
      - run:
          name: Updating package versions
          command: ./release-scripts/update-dev-versions.sh
      - run:
          name: Pruning Snyk CLI dependencies
          command: npx ts-node ./release-scripts/prune-dependencies-in-packagejson.ts
      - run:
          name: Building binaries
          command: |
            cat package.json
            ./release-scripts/make-binaries.sh
            ls -la ./binary-releases
      - store_artifacts:
          path: ./binary-releases
      - run:
          name: Validating binaries
          working_directory: ./binary-releases
          command: ../release-scripts/validate-checksums.sh
      - pack_snyk_cli
      - store_artifacts:
          path: ./dist-pack
  prod-release:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - run:
          name: Should I release?
          command: ./release-scripts/should-i-release.sh
      - gh/setup:
          token: GH_TOKEN
          version: 1.9.2
      - aws-cli/install:
          version: 2.2.32
      - install_release_dependencies
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: .
      - run:
          name: Updating package versions
          command: |
            ./release-scripts/update-versions.sh
            git update-index --skip-worktree -- ./lerna.json
            git update-index --skip-worktree -- ./package.json
            git update-index --skip-worktree -- ./packages/snyk-protect/package.json
      - run:
          name: Pruning Snyk CLI dependencies
          command: npx ts-node ./release-scripts/prune-dependencies-in-packagejson.ts
      - run:
          name: Bumping versions and publishing packages
          command: npx lerna publish minor --yes --no-push --no-git-tag-version --exact
      - run:
          name: Building binaries
          command: |
            ./release-scripts/make-binaries.sh
            ls -la ./binary-releases
      - store_artifacts:
          path: ./binary-releases
      - run:
          name: Validating binaries
          working_directory: ./binary-releases
          command: ../release-scripts/validate-checksums.sh
      - run:
          name: Generating release notes
          command: npx conventional-changelog-cli -p angular -l -r 1 > RELEASE_NOTES.txt
      - run:
          name: Publishing binaries
          command: ./release-scripts/upload-artifacts.sh
      - run:
          name: Handling failed release
          command: ./release-scripts/handle-failed-release.sh
          when: on_fail

workflows:
  version: 2
  test_and_release:
    jobs:
      - lint:
          name: Lint
      - build:
          name: Build

      - unit-test:
          name: Unit Test
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
          requires:
            - Build # needed for importing local packages like @snyk/fix

      - acceptance-test:
          name: Acceptance Test (Node v<< matrix.node_version >>)
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
          requires:
            - Unit Test
          matrix:
            parameters:
              node_version: ['12.22.5', '14.17.5']

      - tap-test:
          name: Tap Test (Node v<< matrix.node_version >>)
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
          requires:
            - Build
          matrix:
            parameters:
              node_version: ['12.22.5', '14.17.5']

      - regression-test:
          name: Regression Tests
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
          requires:
            - Build

      - dev-release:
          name: Development Release
          filters:
            branches:
              ignore:
                - master
          requires:
            - Lint
            - Build
      # - prod-release:
      #     name: Production Release
      #     context: nodejs-app-release
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - Lint
      #       - Build
