version: 2.1

orbs:
  win: circleci/windows@2.2.0

defaults: &defaults
  parameters:
    node_version:
      type: string
      default: ''
    use_npm7:
      type: boolean
      default: true
  working_directory: ~/snyk

windows_defaults: &windows_defaults
  environment:
    npm_config_loglevel: silent
  executor:
    name: win/default

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install
  update_local_npmrc_linux:
    description: Update local .npmrc file (Linux)
    steps:
      - run:
          name: Update local .npmrc file (Linux)
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  build_ts:
    description: Build js files from ts
    steps:
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/
  install_gradle_windows:
    description: Install gradle
    steps:
      - run: choco install gradle
  install_maven_windows:
    description: Install maven
    steps:
      - run: choco install maven
  install_sbt_windows:
    description: Install SBT
    steps:
      - run: choco install sbt
  install_sdkman_unix:
    description: Install SDKMAN
    steps:
      - run:
          name: Installing SDKMAN
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
  install_jdk_unix:
    description: Install JDK
    steps:
      - run:
          name: Installing JDK
          command: sdk install java $(sdk list java | grep -o -m1 "11\.[0-9\.]\+hs-adpt")
  install_gradle_unix:
    description: Install gradle
    steps:
      - run:
          name: Installing Gradle
          command: sdk install gradle 6.4.1
  install_maven_unix:
    description: Install maven
    steps:
      - run:
          name: Installing maven
          command: sdk install maven 3.6.3
  install_sbt_unix:
    description: Install SBT
    steps:
      - run:
          name: Installing sbt
          command: sdk install sbt 1.3.12
  install_node_windows:
    description: Install the given Node version on Windows using Chocolatey
    parameters:
      node_version:
        type: string
        default: ''
    steps:
      - run:
          name: Install Node with Chocolatey
          command: |
            $current_node_version = node --version
            nvm uninstall $current_node_version
            choco install nodejs --version=<< parameters.node_version >>
  install_shellspec:
    description: Install Shellspec
    steps:
      - run: curl -fsSL https://git.io/shellspec | sh -s -- -y
      - run: sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
      - run: sudo apt-get install jq
  show_node_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version
  generate_help:
    description: Generate CLI help files
    steps:
      - run:
          name: Run CLI help text builder
          command: npm run generate-help
  install_github_cli:
    description: Install GitHub CLI (gh)
    steps:
      - run:
          name: Install GitHub CLI (gh)
          command: |
            mkdir gh-download
            curl -Lo ./gh-download/gh_1.3.1_linux_amd64.tar.gz https://github.com/cli/cli/releases/download/v1.3.1/gh_1.3.1_linux_amd64.tar.gz
            tar -xf ./gh-download/gh_1.3.1_linux_amd64.tar.gz --directory gh-download
            chmod a+x gh-download/gh_1.3.1_linux_amd64/bin/gh
            mkdir -p /home/circleci/bin
            mv gh-download/gh_1.3.1_linux_amd64/bin/gh /home/circleci/bin
            which gh
            gh --version

jobs:
  regression-test:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          # docker_layer_caching: true
      - install_shellspec
      - run:
          name: Install npm@7
          command: |
            sudo npm install -g npm@7
      - show_node_version
      - update_local_npmrc_linux
      - install_deps
      - build_ts
      - generate_help
      - run:
          name: Run auth
          command: npm run snyk-auth
      - run:
          name: Run tests
          command: npm run test:common
      - run:
          name: Clear Snyk config
          command: rm ~/.config/configstore/snyk.json
      - run:
          name: Clear node_modules
          command: rm -rf node_modules/
      - run:
          name: Install only production dependencies
          command: npx npm@6 install # kludge because npm@7 will invoke the lifecycle scripts (thus running prepare -> tsc) even if we use --ignore-scripts
          environment:
            NODE_ENV: production
      - run:
          name: npm install for fixture project
          working_directory: ~/snyk/test/fixtures/basic-npm
          command: npm install
      - run:
          name: Setup alias for snyk
          working_directory: ~/snyk/
          command: sudo ./test/smoke/setup-alias-for-snyk.sh
      - run:
          name: Run shellspec
          working_directory: ~/snyk/test/smoke
          command: |
            echo "Checkout the README in test/smoke folder for more details about this step"
            unset SNYK_API
            unset SNYK_API_KEY
            shellspec -f d -e REGRESSION_TEST=1

  test-windows:
    <<: *defaults
    <<: *windows_defaults
    steps:
      - run: git config --global core.autocrlf false
      - install_gradle_windows
      - install_maven_windows
      - install_sbt_windows
      - show_node_version
      - install_node_windows:
          node_version: << parameters.node_version >>
      - show_node_version
      - checkout
      - attach_workspace:
          at: ~/snyk
      - when:
          condition: << parameters.use_npm7 >>
          steps:
            - run: npm install -g npm@7
      - show_node_version
      - run:
          name: Update local .npmrc file (Windows)
          command: echo "//registry.npmjs.org/:_authToken=$env:NPM_TOKEN" >> .npmrc
      - run:
          name: Install dependencies (Windows)
          command: npm install --ignore-scripts # ignore-scripts required because of postinstall script in snyk-resolve-deps package
      - build_ts
      - run:
          name: npm version
          command: npm --version
      - run:
          name: Run auth
          shell: bash.exe
          command: npm run snyk-auth-windows
      - run:
          name: Run tests
          command: npm run test-windows

  test-unix:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - install_sdkman_unix
      - install_jdk_unix
      - install_gradle_unix
      - install_maven_unix
      - install_sbt_unix
      - show_node_version
      - checkout
      - attach_workspace:
          at: ~/snyk
      - when:
          condition: << parameters.use_npm7 >>
          steps:
            - run: sudo npm install -g npm@7
      - show_node_version
      - update_local_npmrc_linux
      - install_deps
      - build_ts
      - run:
          name: npm version
          command: npm --version
      - run:
          name: Run auth
          command: npm run snyk-auth
      - run:
          name: Run tests
          command: npm test

  dev-release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - install_github_cli
      - run:
          name: Install npm@7
          command: |
            sudo npm install -g npm@7
      - show_node_version
      - run:
          name: Setup Lerna
          command: sudo npm install -g lerna
      - update_local_npmrc_linux
      - install_deps
      - generate_help
      - run:
          name: Update package versions
          command: ./release-scripts/update-versions.sh
      - run:
          name: Make git ignore changes relating to version updates
          command: |
            git update-index --skip-worktree -- ./lerna.json
            git update-index --skip-worktree -- ./package.json
            git update-index --skip-worktree -- ./packages/snyk-protect/package.json
            git update-index --skip-worktree -- ./.npmrc
      - run:
          name: Dev Lerna Publish
          command: |
            dev_version="1.0.0-dev-${CIRCLE_SHA1}"
            echo "dev_version: ${dev_version}"
            lerna publish ${dev_version} --yes --no-push --no-git-tag-version --dist-tag hammertest
      - run:
          name: Install osslsigncode
          command: sudo apt-get install -y osslsigncode
      - run:
          name: Create Binaries
          command: |
            ./release-scripts/make-binaries.sh
            ls -la ./binary-releases
      - store_artifacts:
          path: ./binary-releases
      - run:
          name: Validate binary release checksums
          working_directory: ~/snyk/binary-releases
          command: |
            ../release-scripts/validate-checksums.sh

  release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          # docker_layer_caching: true
      - run:
          name: Should I release?
          command: |
            echo "Considering these commits:"
            git --no-pager log $(git describe --tags --abbrev=0 @^)..@ --pretty=format:'%s' --no-merges
            echo "\n---\nChecking for feat, fix or revert commit"
            git log $(git describe --tags --abbrev=0 @^)..@ --pretty=format:'%s' --no-merges | grep -Ei "^(feat|fix|revert)"
            if [ "$?" = "1" ]; then
              echo "No changes to release, stopping"
              circleci-agent step halt
            fi
      - install_github_cli
      - run:
          name: Install npm@7
          command: |
            sudo npm install -g npm@7
      - show_node_version
      - run:
          name: Setup Lerna
          command: sudo npm install -g lerna
      - update_local_npmrc_linux
      - install_deps
      - generate_help
      - run:
          name: Update package versions
          command: ./release-scripts/update-versions.sh
      - run:
          name: Make git ignore changes relating to version updates and to .npmrc
          command: |
            git update-index --skip-worktree -- ./lerna.json
            git update-index --skip-worktree -- ./package.json
            git update-index --skip-worktree -- ./packages/snyk-protect/package.json
            git update-index --skip-worktree -- ./.npmrc
      - run:
          name: Lerna Publish
          command: |
            lerna publish minor --yes --no-push --no-git-tag-version
      - run:
          name: Install osslsigncode
          command: sudo apt-get install -y osslsigncode
      - run:
          name: Create Binaries
          command: |
            ./release-scripts/make-binaries.sh
            ls -la ./binary-releases
      - store_artifacts:
          path: ./binary-releases
      - run:
          name: Validate binary release checksums
          working_directory: ~/snyk/binary-releases
          command: |
            ../release-scripts/validate-checksums.sh
      - run:
          name: Create a GitHub release
          command: |
            latest_version=$(cat lerna.json | jq .version -r)
            new_tag="v${latest_version}"
            npx conventional-changelog-cli -p angular -l -r 1 > RELEASE_NOTES.txt
            gh release create ${new_tag} --title "${new_tag}" --notes-file RELEASE_NOTES.txt
      - run:
          name: Add Assets to GitHub Release
          command: |
            gh_latest_release_tag=$(gh api repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest | jq .tag_name -r)
            echo "gh_latest_release_tag: ${gh_latest_release_tag}"
            gh release upload $gh_latest_release_tag \
              binary-releases/snyk-alpine \
              binary-releases/snyk-linux \
              binary-releases/snyk-macos \
              binary-releases/snyk-win.exe \
              binary-releases/docker-mac-signed-bundle.tar.gz \
              binary-releases/snyk-alpine.sha256 \
              binary-releases/snyk-linux.sha256 \
              binary-releases/snyk-macos.sha256 \
              binary-releases/snyk-win.exe.sha256 \
              binary-releases/docker-mac-signed-bundle.tar.gz.sha256

workflows:
  version: 2
  test_and_release:
    jobs:
      - regression-test:
          name: Regression Test
          context: nodejs-install
          node_version: '12.16.2'
          filters:
            branches:
              ignore:
                - master
      - dev-release:
          name: Dev Release
          node_version: '14'
          context: nodejs-app-release
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-windows:
          name: Windows Tests for Node v12 support
          context: nodejs-install
          node_version: '12.16.2'
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-windows:
          name: Windows Tests for Node v14 support
          context: nodejs-install
          node_version: '14.15.4'
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-windows:
          name: Windows Tests for Node v10 support
          context: nodejs-install
          node_version: '10.23.1'
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-windows:
          name: Windows Tests for Node v8 support
          context: nodejs-install
          node_version: '8.17.0'
          use_npm7: false
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-unix:
          name: Unix Tests for Node v12 support
          context: nodejs-install
          node_version: '12.16.2'
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-unix:
          name: Unix Tests for Node v14 support
          context: nodejs-install
          node_version: '14.15.4'
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-unix:
          name: Unix Tests for Node v10 support
          context: nodejs-install
          node_version: '10.23.1'
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - test-unix:
          name: Unix Tests for Node v8 support
          context: nodejs-install
          node_version: '8.17.0'
          use_npm7: false
          requires:
            - Regression Test
          filters:
            branches:
              ignore:
                - master
      - release:
          name: Release
          context: nodejs-app-release
          node_version: '14.15.4'
          filters:
            branches:
              only:
                - master
