name: 'Check Dependencies'

on:
  pull_request:
    branches: [master]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g npm@7

      - name: npm config get cache
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npx npm@7 config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - run: npx ts-node ./scripts/check-dependencies/cli.ts
