name: Infrastructure as Code CLI alert

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  check_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/iac-cli-alert
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'npm'
      - run: npm ci
      - run: npm start
        env:
          USER_GITHUB_TOKEN: ${{ secrets.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 }}
          IAC_SMOKE_TESTS_SLACK_WEBHOOK_URL: ${{ secrets.IAC_SMOKE_TESTS_SLACK_WEBHOOK_URL }}
